name: poisson_numcodecs CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - uses: s-weighand/setup-conda@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install .

      - name: Test with pytest 
        run: |
          source $HOME/miniforge/bin/activate
          conda activate test-env
          pytest -v
